# Generated by Django 5.1 on 2024-08-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaspi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
        migrations.RenameModel(
            old_name='MagazinesGoods',
            new_name='MagazineGood',
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('goods', models.ManyToManyField(through='kaspi.MagazineGood', to='kaspi.good')),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='magazinegood',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaspi.magazine'),
        ),
        migrations.DeleteModel(
            name='Magazines',
        ),
    ]
